feat(table formatter): formats github issues into a table
emilylzhang/issues pull request #3
Opened 2017-05-30 20:57 UTC by emilylzhang

2017-05-30 21:37 UTC, dmlittle reviewed
@emilylzhang I left a couple of comment. Let me know what you think of them and if you have any questions.

2017-05-30 21:37 UTC, dmlittle commented on lib/issues/table_formatter.ex
> +  import Enum, only: [ each: 2, map: 2, map_join: 3, max: 1 ]
We usually don't import or alias native modules as you lose some context as to where this function is defined. As such we prefer calling `Enum.map` or `Enum.max` rather than importing `Enum` and calling `map` and `max` directly. 

I'm not sure why, and Marcus can comment on this further, but in general we also prefer aliasing modules over importing modules.

2017-05-30 21:37 UTC, dmlittle commented on lib/issues/table_formatter.ex
> +    with data_by_columns = split_into_columns(rows, headers),
This is neat! I didn't know that Elixir had a `with ... do` but it works well in this case.

2017-05-30 21:37 UTC, dmlittle commented on lib/issues/table_formatter.ex
> +    for column <- columns, do:
There is a more functional way of calculating the width of each column. You rarely will need to use a for loop in Elixir (it has the functionality, but it's not needed). 

A more functional approach could be the following:
```elixir
def widths_of(columns) do
  Enum.map(columns, fn column ->
    column
    |> Enum.map(&String.length/1)
    |> Enum.max
  end)
end
```

2017-05-30 21:37 UTC, dmlittle commented on lib/issues/table_formatter.ex
> +    for header <- headers do
Similarly to below, a more functional approach for this function might be:

```elixir
def split_into_columns(rows, headers) do
  Enum.map(headers, fn header ->
    Enum.map(rows, fn row -> printable(row[header]) end)
  end)
end
```

2017-05-30 21:37 UTC, dmlittle commented on lib/issues/cli.ex
> +  import Issues.TableFormatter, only: [print_table_for_columns: 2]
I didn't mention this earlier, but we tend to prefer `alias` over `import`. Marcus might be able to comment as to why (I'm not sure). The reason why I like them better, however, is that I know what module the function you're calling is defined.

If instead of importing `Issues.TableFormatter` you alias it you could use it in the following manner:
```elixir
alias Issues.TableFormatter

user
|> ...
|> TableFormatter.print_table_for_columns(["number", "created_at", "title"])

```

2017-05-30 22:44 UTC, dmlittle approved these changes
Both commits in this PR can be squashed into a single commit. Other than that, it looks great. LGTM!

2017-05-31 15:16 UTC, mgartner requested changes
Overall looks great! I realize you've follow the book on a lot of this, but I've left comments that fit more in line with our unofficial style guidelines.

It looks like you also need to rebase, which I'm happy to walk through with you.

2017-05-31 15:16 UTC, mgartner commented on test/table_formatter_test.exs
> +    assert  List.last(columns) == ["r1+++c4", "r2 c4", "r3 c4", "r4 c4"]
we typically don't align `=` or `==`

2017-05-31 15:16 UTC, mgartner commented on test/table_formatter_test.exs
> +  alias Issues.TableFormatter, as: TF
we generally don't rename alias with `as` because it adds another layer of indirection when trying to comprehend the code

2017-05-31 15:16 UTC, mgartner commented on lib/issues/table_formatter.ex
> +  def printable(str), do: to_string(str)
we typically only make functions public if they are used in other modules, or they have a level of complexity that requires they be individually tested. in this case, it looks like there are a few functions in here that should be private `defp` declarations. we typically puts all private functions at the bottom of a module, leaving public functions at the top to easy see what functions are accessible from a module.

2017-05-31 15:16 UTC, mgartner commented on lib/issues/github_issues.ex
> +  @github_url Application.get_env(:issues, :github_url)
we typically put all module attributes (`@attribute`) at the top of the module

2017-05-31 15:16 UTC, mgartner commented on lib/issues/github_issues.ex
> +  @github_url Application.get_env(:issues, :github_url)
unless they are `@spec` or `@doc`

2017-05-31 15:16 UTC, mgartner commented on test/cli_test.exs
> +    do: %{"created_at" => value, "other_data" => "xxx"}
in general we'd prefer a `do` with an `end` unless its all on one line, so either this:

```elixir
for value <- values do
  %{"created_at" => value, "other_data" => "xxx"}
end
```

or

```elixir
for value <- values, do:  %{"created_at" => value, "other_data" => "xxx"}
```

but, IMHO, `Enum.map` is better suited for this particular case:

```elixir
Enum.map(values, &(%{"created_at" => &1, "other_data" => "xxx"}))
```

2017-05-31 15:16 UTC, mgartner commented on test/cli_test.exs
> +    issues = for issue <- result, do: Map.get(issue, "created_at")
we generally prefer `Enum.map/each/etc` over list comprehension (`for...`) (see below)

2017-05-31 17:43 UTC, merged